vagrant/__init__.py

On Windows 'up' method failed, because /dev/null is not exist.

Fix /dev/null to os.devnull

---

setup.py
tests/test_vagrant.py
tox.ini
vagrant/__init__.py
vagrant/compat.py
vagrant/test.py

Problem
-------
Code base requires additional alignment to be compatible with Python 3.
Solution
--------
* `print` statement to function.
* `subprocess.check_output` in Python 3 returns result of type `bytes`,
expected `str`.
Testing
-------
Added `tox` configuration to run nose tests for both 2.7 and 3.4.
Run command:
tox

Make code base compatible with Python 3.

---

tests/test_vagrant.py
vagrant/__init__.py

See #45 for details on the breaking changes introduced in Vagrant 1.8. This PR accommodates for the changes by stripping out the incompatible lines returned by `--machine-readable`, namely the `metadata` and `ui` lines.
Updates the test suite to handle variance in the number of fields returned by `--machine-readable`, as well as private key paths bounded by double quotes (also a change introduced in 1.8).
All tests are passing under the following Vagrant versions:
* `1.7.2` (listed in the `README`)
* `1.7.4` (previous version)
* `1.8.0` (most recent version)
Resolves #45.

Adds support for Vagrant 1.8

---

vagrant/__init__.py

Just adds support for the `vagrant package` command, which is in vagrant 1.4 at least.  This supports all flags but the `--include` flag since I've never used `--include` and don't fully understand how it works.

Add support for package command (vagrant version >= 1.4)

---

tests/test_vagrant.py
vagrant/__init__.py

In the output from `vagrant up` is information that could be critical to
programatically interfacing with the machine once it's running. This
commit adds a new parameter to `Vagrant.up()` called `output_filter`,
which allows the user to specify a set of regular expressions to look
for in the command's output, and which is returned as a dict. The
user-specified output context manager (given when creating the Vagrant
instance) will still continue to receive the output of the command as
well.

Added ability to filter Vagrant's output for data

---

.github/workflows/tox.yml

GHA has virtualisation and vagrant only on macosx 10.15. So fix things to use it.

Run the CI on macos

---

.github/workflows/tox.yml
tests/test_vagrant.py
tests/test_vagrant_test_case.py
tests/vagrantfiles/multi_box/Vagrantfile
tests/vagrantfiles/multivm_Vagrantfile
tests/vagrantfiles/shell_provision_Vagrantfile
tests/vagrantfiles/single_box/Vagrantfile
tests/vagrantfiles/vm_Vagrantfile

This PR:
- upgrades `generic/alpine310` to `generic/alpine315`
- sets `config.vbguest.auto_update` to `false` because of missing `vbguest`
- replaces static unused box names with `TEST_BOX_NAME`

use generic/alpine315 and configure Vagrant

---

vagrant/test.py

Current setUpOnce function fails with: "IndexError: list index out of range".
Set vm_name parameter of self.vagrant.status in order to find the box to
simplify and fix things.

test: fix setUpOnce

---

tests/vagrantfiles/multi_box/Vagrantfile

This PR:
- adds `vbguest` configuration to `multi_box/Vagrantfile`
- fixes `conf.vm.box` so the boxes can be downloaded

configure vbguest.auto_update and correct vm.box

---

tests/test_vagrant.py

This PR:
- ensures a box is removed during teardown, since failed tests will create halted machines that will be left running w/o a valid Vagrantfile
- add a `try:` so tests don't fail if there isn't any Vagrantfile to remove

ensure boxes are destroyed during teardown and try: unlinking

---

tests/test_vagrant_test_case.py

The VM name is now the box name without the generic/ part, so remove
it.

Fix vm name in SpecificMultiBoxTests

---

vagrant/__init__.py

Vagrant has added some more lines with extra informations
like box-info, Description, so remove them.
This possibly needs to be revisited later to properly deal
with them, for instance, by changing the split() parameter
to 3 and not 4.

Fix vagrant output parsing

---

tests/test_vagrant.py

If there's no Vagrant environment present, ignore the failed `vagrant destroy` command

ignore failed destroy command if there's no environment

---

tests/test_vagrant.py
vagrant/__init__.py

Since python commit for the issue https://bugs.python.org/issue32236,
python will now raise a ValueError for code like ours, so remove
bufsize setting to fix it.
Also fix streaming test test string to be provider agnostic.

Fix streaming with python3+

---

tests/test_vagrant.py
tests/tools/create_dummy_box.sh
tox.ini

test_boxesvm wants to rename generic/alpine315 but vagrant
doesnt allow it. In order to fix it, create a dummy box and
use it.

test_boxesvm: Fix dummy box handling

---

.flake8
tests/test_vagrant.py

This PR:
- adds assert and subprocess ignores to .flake8 since we will be using `assert` and `subprocess`
- fixes flake8/bandit S607/B607 (https://flake8.codes/S607/)

Add additional .flake8 ignores and fix S607/B607

---

tests/test_vagrant.py
vagrant/__init__.py

This PR:
- adds the `vagrant validate` command

add `vagrant validate`

---

tests/test_vagrant.py

This PR:
- adds a Vagrantfile (if it doesn't exist) to configure `vbguest` in order to pass `init()` and `up()` sequence 
- validates the Vagrantfile after `init()`

 configure vbguest and validate Vagrantfile during lifecycle test

---

.github/workflows/tox.yml
setup.cfg
src/vagrant/__init__.py
tests/test_vagrant.py

Wire global-status with its optional --prune option. The testsuite is testing only the box listing since a test for pruning will be quite hard.
Also import pytest-plus and set PYTEST_REQPASS to ensure we're running the right number of checks.

Global status support

---

tox.ini

Without this PYTEST_REQPASS would be ignored.

tox.ini: pass PYTEST_* env variables

---

.github/workflows/tox.yml

Add caching for the vagrant boxes to avoid errors like:
"An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 429"
Fixes: #128

.github/workflows/tox.yml: add vagrant boxes caching

---

.pre-commit-config.yaml

This is not necessary and fails on recent distros.
Signed-off-by: Leonard Crestez <cdleonard@gmail.com>

pre-commit: Remove default_language_version python3.8

---

.github/workflows/release.yml
.github/workflows/tox.yml

This PR:
- updates GHA since Node.js 12 actions are deprecated.
- related https://github.com/shyim/junit-report-annotations-action/issues/7

Update Github Actions

---

.flake8

See https://github.com/pycontribs/python-vagrant/actions/runs/3629499055/jobs/6121771161#step:10:108

Remove comments from flake8 extend-ignore

---

tox.ini

Set `allowlist_externals` to `sh`, `/home/runner/work/python-vagrant/python-vagrant/tests/tools/create_dummy_box.sh` and `/Users/runner/work/python-vagrant/python-vagrant/tests/tools/create_dummy_box.sh`
See https://github.com/pycontribs/python-vagrant/actions/runs/3622456363/jobs/6107188602#step:10:21 and https://tox.wiki/en/latest/config.html#allowlist_externals

Allowlist in glob style

---

.github/workflows/tox.yml

This PR:
- replaces `macos-10.15` with `macos-12` in the GH workflows, due to deprecation. See https://github.com/actions/runner-images/issues/5583

replace macos-10.15 with macos-12

---

pyproject.toml
tox.ini

This PR:
- removes `no-self-use` since it was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers.
- removes a line comment from tox.ini since it failed with `ConfigError: usedevelop: boolean value 'true # needed for coverage' needs to be 'True' or 'False'`

Update pyproject and tox

---

.github/workflows/tox.yml
src/vagrant/__init__.py
tests/test_vagrant.py

So far, a SSH command returning with a non-zero exit code would cause an exception:
```
Traceback (most recent call last):
File "/home/georg/Work/git/salt-formulas/../scullery/scullery.py", line 276, in <module>
main_interactive()
File "/home/georg/Work/git/salt-formulas/../scullery/scullery.py", line 239, in main_interactive
runapply(testconf['apply'], target)
File "/home/georg/Work/git/salt-formulas/../scullery/scullery.py", line 144, in runapply
sshout = v.ssh(command='sudo {} {}'.format(saltcmd, state))
File "/usr/lib/python3.10/site-packages/vagrant/__init__.py", line 869, in ssh
return self._run_vagrant_command(cmd)
File "/usr/lib/python3.10/site-packages/vagrant/__init__.py", line 1105, in _run_vagrant_command
subprocess.check_output(
File "/usr/lib64/python3.10/subprocess.py", …
```

Handle failing SSH commands gracefully
